name          'puppet-xlrelease'
version       '0.0.1'
source        'https://github.com/WianVos/puppet-xlrelease.git'
author        'Wian Vos'
license       'Apache 2.0'
summary       'An installation and intergration module for Xl-Release by xebialabs'
description   ''
project_page  'https://github.com/WianVos/puppet-xlrelease'

dependency 'puppetlabs/stdlib'
