name          'puppet-xlrelease'
version       '1.0.0'
source        'https://github.com/xebialabs/puppet-xlrelease.git'
author        'Wian Vos'
license       'Apache 2.0'
summary       'An installation and intergration module for Xl-Release by xebialabs'
description   ''
project_page  'https://github.com/WianVos/puppet-xlrelease'

dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'puppetlabs/inifile', '>= 1.0.0'
dependency 'puppetlabs/concat', '>= 1.1.0'