name          'puppet-xlrelease'
version       '1.0.0'
source        'https://github.com/xebialabs/puppet-xlrelease.git'
author        'xebialabs'
license       'Apache v2.0'
summary       'An installation and intergration module for XL Release by xebialabs'
description   ''
project_page  'https://github.com/xebialabs/puppet-xlrelease'

dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'puppetlabs/inifile', '>= 1.0.0'
dependency 'puppetlabs/concat', '>= 1.1.0'
